### ISSUE TITLE
Add .form files to the repo

### ISSUE THREAD

**Issue by etr2460** [anmart/UniversalCardGameRandomizer#1]
I'm having trouble modifying the UIs in netbeans, I think it's because I need the .form files to edit the UI source code.

**Comment by anmart** [comment]
I have a separate project for this in netbeans where a couple files are just shared. I have no idea how to manage it better between the two. 

Here's the .form for PTCG1_UI. let me know if it works and I'll include it in my next commit

[PTCG1_UI_AUTO.zip](https://github.com/anmart/UniversalCardGameRandomizer/files/367649/PTCG1_UI_AUTO.zip)

**Comment by etr2460** [comment]
Adding that file worked great. If you can add all the .form files in the
next commit, that would make stuff a lot easier. Thanks!

**Comment by anmart** [comment]
That's the only .form file that currently exists (The other UIs are either empty or hand written) but I'll remember to add them from now on! :P
