### ISSUE TITLE
Mr. Mime No Damage Bug

### ISSUE THREAD

**Issue by SubZero5268** [anmart/UniversalCardGameRandomizer#11]
When using Comet Punch with Meowth and Surf with Lickitung, Mr. Mime takes no damage despite neither being a Resistance on his card. Meowth is set to Fighting type and Lickitung is Colorless. Playing through Retroarch on Gambatte core!

**Comment by anmart** [comment]
Thank you for letting me know ! I haven't really touched poketcg or this randomizer in a while, but I will try to take a look.

**Comment by anmart** [comment]
Ah just as I figured. A lot of effects in poketcg are [hardcoded](https://github.com/pret/poketcg/blob/8b37eba4d314a605a1961d7641e0f98bd5da3fde/src/home/substatus.asm#L95) to the relevant pokemon. I tried to catch what I could but I'm sure there are tons I missed. 

There are a few people working on "better poketcg" hacks. I've thought about going through and doing that as well, fixing all the hard coded junk, but I'll probably find a hack I like and contribute to that, then pull it into the randomizer in any ways I can.

Thank you again for pointing this out!

**Comment by SubZero5268** [comment]
Hey, thanks for getting back to me!

Sorry to drag you in here after so long, it was one of those things where I didn't know if the project was fully dormant or not, so in the interest of playing it safe I decided to report it just in case!

If you don't mind me asking while I'm here, could you point me in the direction of some of these other hacks? I'd like to keep my eye on them!

**Comment by anmart** [comment]
I appreciate it! I'd love to get back to this project *Eventually*

[Here's Sha0den's Poketcg V2](https://github.com/Sha0den/poketcg_v2). There's also a [poketcg hacking discord server](https://discord.gg/T2TSdZS9) that you may be able to learn more from !

**Comment by SubZero5268** [comment]
That is much appreciated! Thanks a ton for the guidance :D
