### ISSUE TITLE
Imakuni?!

### ISSUE THREAD

**Issue by Snowbear22** [anmart/UniversalCardGameRandomizer#7]
Imakuni?! when beaten does not trigger additional packs nor cause the player to lose cards after a win. Not sure if intentional.

**Comment by anmart** [comment]
I somehow didn't realize until now, but this isn't an issue for the randomizer. This is an issue for the [poketcg-hacks](https://github.com/anmart/poketcg-hacks) repo.

Issue moved to here: https://github.com/anmart/poketcg-hacks/issues/5
